### PR TITLE
WIP: Feature - Issue #659 - Update tX to use ORM for RDS manifest table

### PR DESCRIPTION
**Pull request by richmahn**
WIP due to still testing it on dev (and need to find a way to have a dev RDS to test)

### CODE REVIEW

**Comment by jag3773** [comment]
@richmahn I'd suggest testing with Travis.  Have Travis install mysql and load it with test data from a sql file, then query it.  Travis DB info at https://docs.travis-ci.com/user/database-setup/ .

**Comment by richmahn** [comment]
Travis does fine with my branch and running tests, yet I just make the DB connection string be `sqlite:///:memory:` so it uses sqlite instead of mysql for the tests. But what I'm talking about is users, from myself to my code reviewer to just being able to play around being on test. Travis has ran my code, but I haven't been able to. I would like to commit something to DCS and see its project page and a change in the manifest table, etc.

**Comment by richmahn** [comment]
Travis never used our pipeline (test environment, dev environment) anyway.... just use humans.... well, except for the integration tests and to deploy our code. I'm talking about for US.

**Comment by richmahn** [comment]
Reverted in another PR

**Pull request closed without merging**
